linters:
  enable:
    - gofumpt
    - durationcheck
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gochecknoglobals
    - errorlint
    - exhaustive
    - revive
    # - gosec
issues:
  max-same-issues: 0
  exclude-rules:
    # # Exclude some linters from running on tests files.
    # - path: _test\.go
    #   linters:
    #     - revive
