version: "2"
linters:
  default: standard
  enable:
    - durationcheck
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gochecknoglobals
    - errorlint
    - exhaustive
    - revive
  settings:
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    # Exclude some linters from running on tests files.
    rules:
      - path: _test\.go
        linters:
          - revive
formatters:
  enable:
    - gofumpt
issues:
  max-same-issues: 0
